# Generated by Django 3.1.7 on 2021-05-16 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210516_0253'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='location',
            field=models.CharField(default='Almaty', max_length=200),
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
