# Generated by Django 3.1.7 on 2021-05-15 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_', '0002_auto_20210516_0253'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['username'], 'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
    ]
